// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxNu4YZgSmGvlBOPyMoWDrJDOyJLcfb4',
    appId: '1:764335365710:web:b2c32c0222cb6e26436d1f',
    messagingSenderId: '764335365710',
    projectId: 'mindfulphone-312',
    authDomain: 'mindfulphone-312.firebaseapp.com',
    storageBucket: 'mindfulphone-312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKkD16jE3FAVZWB3YCoOSmBvnIvSTxrxs',
    appId: '1:764335365710:android:bd530090fe93495e436d1f',
    messagingSenderId: '764335365710',
    projectId: 'mindfulphone-312',
    storageBucket: 'mindfulphone-312.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxNu4YZgSmGvlBOPyMoWDrJDOyJLcfb4',
    appId: '1:764335365710:web:0d990875730c54f6436d1f',
    messagingSenderId: '764335365710',
    projectId: 'mindfulphone-312',
    authDomain: 'mindfulphone-312.firebaseapp.com',
    storageBucket: 'mindfulphone-312.firebasestorage.app',
  );
}
